# Generated by Django 5.2.4 on 2026-06-30 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID уровня в GD')),
                ('global_demonlist_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID уровня в глобале')),
                ('name', models.CharField(max_length=100, verbose_name='Название уровня')),
                ('place', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('published', models.CharField(default='None', max_length=100, verbose_name='Креатор')),
                ('thumbnail_url', models.URLField(blank=True, null=True, verbose_name='Изображение')),
                ('verifier', models.CharField(default='None', max_length=100, verbose_name='Верифер')),
                ('creator', models.CharField(default='None', max_length=100, verbose_name='Креатор')),
                ('description', models.CharField(default='None', max_length=500, verbose_name='Описание')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Видео')),
                ('completion_points_pc', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Очки за прохождения(ПК)')),
                ('list_points_pc', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Очки за рекорд(ПК)')),
                ('list_percentage_pc', models.PositiveIntegerField(default=0, verbose_name='Процент листа(ПК)')),
                ('completion_points_mobile', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Очки за прохождения(Моб.)')),
                ('list_points_mobile', models.FloatField(default=0, verbose_name='Очки за рекорд(Моб.)')),
                ('list_percentage_mobile', models.PositiveIntegerField(default=0, verbose_name='Процент листа(Моб.)')),
            ],
            options={
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('global_demonlist_user_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id игрока в глобале')),
                ('region', models.CharField(blank=True, choices=[('RB', 'Республика Бурятия'), ('RSYA', 'Республика Саха (Якутия)'), ('ZK', 'Забайкальский Край'), ('KK', 'Камчатский Край'), ('PK', 'Приморский Край'), ('KHK', 'Хабаровский Край'), ('AO', 'Амурская Область'), ('MO', 'Магаданская Область'), ('SO', 'Сахалинская Область'), ('JAO', 'Еврейская Автономная Область'), ('CHAO', 'Чукотский Автономный Округ')], max_length=50, null=True, verbose_name='Регион')),
                ('score_pc', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Очки (ПК)')),
                ('score_mobile', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Очки (Моб.)')),
                ('gd_account_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID аккаунта в GD (AccountID)')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('hardest_mobile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_mobile_hardest', to='demonlist.level', verbose_name='Сложнейший уровень на мобиле')),
                ('hardest_pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_pc_hardest', to='demonlist.level', verbose_name='Сложнейший уровень на пк')),
            ],
        ),
        migrations.CreateModel(
            name='RecordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=100, verbose_name='Прогресс')),
                ('video', models.URLField(verbose_name='Видео (YouTube)')),
                ('device', models.CharField(choices=[('PC', 'ПК'), ('Mobile', 'Телефон')], max_length=20, verbose_name='Устройство')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметка модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonlist.level', verbose_name='Уровень')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonlist.user', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Заявка на рекорд',
                'verbose_name_plural': 'Заявки на рекорды',
            },
        ),
        migrations.CreateModel(
            name='DiscordLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления в ЛС')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_link', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт на сайте')),
                ('gd_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_link', to='demonlist.user', verbose_name='Профиль игрока в листе')),
            ],
        ),
        migrations.CreateModel(
            name='Victor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Прогресс')),
                ('device', models.CharField(blank=True, choices=[('PC', 'ПК'), ('Mobile', 'Телефон')], max_length=20, null=True, verbose_name='Устройство')),
                ('youtube', models.URLField(blank=True, null=True)),
                ('is_first_victor', models.BooleanField(default=False, verbose_name='Первый виктор уровня')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonlist.level')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonlist.user')),
            ],
        ),
    ]
